FROM nginx:latest

WORKDIR /usr/share/nginx/html

# 複製導出的所有檔案 (export/web 資料夾中的所有內容)
COPY ./export/web .

# 複製自訂 nginx 配置檔
COPY ./nginx.conf /etc/nginx/nginx.conf

# 暴露連接埠
EXPOSE 80

# 啟動 Nginx
CMD ["nginx", "-g", "daemon off;"]
